import Head from 'next/head'
import App from '../components/App'

export default function Home() {
  return (
    <>
      <Head>
        <title>Austin Condiff – Creative UI Developer &amp; UX/Ui Designer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta httpEquiv="Content-Type" content="text/html; charset=utf-8"></meta>
        <meta
          name="description"
          content="The Portfolio of Austin Condiff, UX/UI Designer & Front-end Developer – I design and develop beautiful yet functional interactive user experiences that provide both customer value and product success."
        ></meta>
        <meta
          name="keywords"
          content="Austin, Condiff, Cundiff, Austin Condiff, Austin Cundiff, website, design, developement, resume, portfolio, professional, bio, about, hire, history, education, skills, skillset, user, experience, sketch, react, reactjs, ux, ui, interface, designer, front-end, frontend, developer, engineer, creative"
        ></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, user-scalable=no, viewport-fit=cover"
        ></meta>
        <meta httpEquiv="content-language" content="en"></meta>
        <meta property="og:title" content="The Portfolio of Austin Condiff - UX/UI Designer & Developer"></meta>
        <meta property="og:image" content="http://austincondiff.com/assets/img/img-preview.jpg"></meta>
        <meta
          property="og:description"
          content="I design and develop beautiful yet functional interactive user experiences that provide both customer value and product success."
        ></meta>
        <meta property="og:url" content="http://austincondiff.com"></meta>
        <meta name="twitter:image" content="https://austincondiff.com/assets/img/img-preview.jpg"></meta>
        <meta name="twitter:image:src" content="https://austincondiff.com/assets/img/img-preview.jpg"></meta>
        <meta name="twitter:card" content="summary_large_image"></meta>
        <meta name="twitter:site" content="@austincondiff"></meta>
        <meta name="twitter:creator" content="@austincondiff"></meta>
        <meta name="twitter:title" content="The Portfolio of Austin Condiff - UX/UI Designer & Developer"></meta>
        <meta
          name="twitter:description"
          content="I design and develop beautiful yet functional interactive user experiences that provide both customer value and product success."
        ></meta>
        <meta name="theme-color" content="#066fff"></meta>
        <meta name="apple-mobile-web-app-status-bar-style" content="#066fff"></meta>
        <meta name="apple-mobile-web-app-capable" content="yes" />
      </Head>
      <App />
    </>
  )
}
